
#includ_old: package:effective_dart/analysis_options.yaml
include: package:pedantic/analysis_options.1.9.0.yaml

#linter:
#  rules:
#    camel_case_types: true
#    package_api_docs: true
#    prefer_single_quotes: true
#    avoid_catches_without_on_clauses: false
#
#analyzer:
#  exclude:
#    - test/.test_coverage.dart